source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'cancancan'
gem 'hirb-unicode'
gem 'sass-rails'
gem 'less-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'spring', group: :development
gem 'uglifier', '>= 1.3.0'
gem 'rolify'
gem 'barby'
gem 'chunky_png'
gem 'rack-cors', require: 'rack/cors'
gem 'rails_best_practices'
gem 'digest'
gem 'pg'
gem 'thin'
gem 'active_model_serializers', '~> 0.10.0.rc4'
gem 'json'
gem 'logger'
gem 'bower-rails'
gem 'haml-rails'
gem 'haml'
gem 'exception_notification'
gem 'erb2haml'
gem 'devise_lastseenable'
gem 'faker'
gem 'therubyracer'
gem 'validates_timeliness', '3.0.14'
gem 'devise'
gem 'sinatra'
gem 'sidekiq'
gem 'clockwork'
gem 'httpclient'
gem 'redis'
gem 'figaro'
gem 'unicorn'

group :development, :test do
  gem 'better_errors'
  gem 'guard'
  gem 'spring-commands-rspec'
  gem 'rspec-rails', '~> 3.1'
  gem 'rb-fsevent' # if `uname` =~ /Darwin/
  gem 'guard-rspec', require: false
  gem 'guard-bundler', require: false
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'factory_girl'
  gem 'quiet_assets'
  gem 'rubocop', require: false
  gem 'rubocop-rspec'
  gem 'guard-rubocop'
  gem 'capistrano-rvm'
  gem 'capistrano-rails'
  gem 'capistrano3-unicorn'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'timecop'
  gem 'launchy'
end
