#!/bin/bash
# faye init file for faye
#
# chkconfig: - 50 50
# description: faye
#
# processname: faye
# config: faye.ru
# pidfile: /www/practica.cc/tmp/faye.pid

### BEGIN INIT INFO
# Provides: faye
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: start and stop faye daemon
# Description: faye
### END INIT INFO

set -e

AS_USER=w3practica
RAILS_ENV=production
APP_ROOT=/www/practica.cc/current
FAYE_CONF="faye.ru"
PID=/www/practica.cc/tmp/faye.pid
CMD="cd /www/practica.cc/current; RAILS_ENV=$RAILS_ENV bundle exec rackup $FAYE_CONF -s thin -E $RAILS_ENV -D --pid $PID -p 9293"

set -u

OLD_PIN="$PID.oldbin"

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
}

run () {
  if [ "$(id -un)" = "$AS_USER" ]; then
    eval $1
  else
    su -c "$1" - $AS_USER
  fi
}

case "$1" in
start)
  sig 0 && echo >&2 "Already running" && exit 0
  run "$CMD"
  ;;
stop)
  sig QUIT && exit 0
  echo >&2 "Not running"
  ;;
force-stop)
  sig TERM && exit 0
  echo >&2 "Not running"
  ;;
restart|reload)
  sig HUP && echo reloaded OK && exit 0
  echo >&2 "Couldn't reload, starting '$CMD' instead"
  run "$CMD"
  ;;
*)
  echo >&2 "Usage: $0 <start|stop|restart|force-stop>"
  exit 1
  ;;
esac
