defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: corehook
  password: corehook
  schema_search_path: public
  encoding: utf8
  template: template0
  pool: 30
  timeout: 5000

development:
  <<: *defaults
  database: practice_dev

staging:
  <<: *defaults
  username: pract_dev
  database: pract_dev
  host: 89.208.147.167
  password: WigtotEughWyroj1

production:
  <<: *defaults
  username: pract_dev
  database: pract_dev
  host: 89.208.147.167
  password: WigtotEughWyroj1


test: &test
  <<: *defaults
  database: practice_test